import type { DimensionId, RoleId, RoleProfile } from './types'

const operatorDimensions: DimensionId[] = ['culture', 'prevent', 'training', 'immersive', 'operational']
const operatorInformation: DimensionId[] = ['knowledge', 'advisor', 'intelligence', 'regional']
const terminal = 'APM Terminals Buenos Aires'

const operator = (
  id: RoleId,
  name: string,
  shortName: string,
  mandatoryModules: string[],
  conditionalModules: string[],
  optionalModules: string[],
): RoleProfile => ({
  id,
  name,
  shortName,
  demoUser: `Demo ${shortName}`,
  initials: shortName.split(' ').map((word) => word[0]).join('').slice(0, 2).toUpperCase(),
  level: 'operator',
  decisionFocus: 'Que hago ahora, que control verifico y cuando detengo la tarea.',
  terminal,
  campaign: id === 'operator-lashing' ? 'Trinca y Destrinca Segura' : 'Ruta operativa por especialidad',
  mandatoryModules,
  conditionalModules,
  optionalModules,
  visibleDimensions: operatorDimensions,
  informationalDimensions: operatorInformation,
})

export const roleProfiles: RoleProfile[] = [
  {
    ...operator(
      'operator-lashing',
      'Operario de Trinca y Destrinca',
      'Operario Trinca',
      ['Inspeccion de pasarela', 'Transportes', 'Cargas suspendidas', 'Combate de incendios', 'Trinca y destrinca', 'Trabajo en jaula'],
      ['Trabajos en altura', 'Energia almacenada', 'Contratistas'],
      ['Simulacion de atrapamientos', 'Comunicacion de cuadrilla', 'Ergonomia y fatiga'],
    ),
    demoUser: 'Carlos Medina',
    initials: 'CM',
  },
  operator(
    'operator-sts',
    'Operador de Grua STS / QC',
    'Operador STS',
    ['Induccion HSSE', 'Operacion segura STS/QC', 'Cargas suspendidas', 'Comunicacion operacional', 'Zonas de exclusion', 'Emergencias'],
    ['Trabajos en altura', 'Energia almacenada', 'Carga OOG / peligrosa', 'Clima adverso'],
    ['Simulacion de izaje', 'Fatiga y decisiones', 'Casos de carga suspendida'],
  ),
  operator(
    'operator-yard-equipment',
    'Operador RTG / RMG / Reach Stacker',
    'Operador RTG',
    ['Induccion HSSE', 'Operacion segura del equipo', 'Transportes', 'Puntos ciegos', 'Checklist pre-uso', 'Estacionamiento seguro'],
    ['Cargas suspendidas', 'Carga peligrosa', 'Energia almacenada', 'Clima adverso'],
    ['Conduccion defensiva', 'Zonas calientes del patio', 'Casos de colision y vuelco'],
  ),
  operator(
    'operator-tractor',
    'Operador Terminal Tractor / ITV',
    'Operador Tractor',
    ['Induccion HSSE', 'Conduccion defensiva', 'Transportes', 'Separacion peaton-vehiculo', 'Radio y rutas autorizadas'],
    ['Carga peligrosa', 'Operacion en muelle', 'Trabajo nocturno', 'Clima adverso'],
    ['Fatiga y distraccion', 'Simulador de conduccion', 'Comunicacion breve por radio'],
  ),
  operator(
    'operator-gate',
    'Operador Gate / Inspeccion',
    'Operador Gate',
    ['Induccion HSSE', 'Transportes', 'Control de acceso', 'Separacion fisica', 'Condiciones inseguras', 'Emergencias'],
    ['Carga peligrosa', 'Inspeccion fisica', 'Alto flujo vehicular'],
    ['Atencion segura a terceros', 'Ingresos no autorizados', 'Documentacion peligrosa'],
  ),
  operator(
    'operator-reefer',
    'Operador Reefer / Tecnico de Patio',
    'Tecnico Reefer',
    ['Induccion HSSE', 'Seguridad electrica', 'Energia almacenada', 'EPP especifico', 'Transportes', 'Checklist de conexion'],
    ['Trabajos en altura', 'LOTO', 'Refrigerantes', 'Trabajo nocturno'],
    ['Respuesta ante falla reefer', 'Cables danados', 'Housekeeping'],
  ),
  operator(
    'operator-maintenance',
    'Operador de Mantenimiento',
    'Mantenimiento',
    ['Induccion HSSE', 'Energia almacenada', 'LOTO', 'Permiso de trabajo', 'Herramientas seguras'],
    ['Trabajos en altura', 'Espacios confinados', 'Trabajo en caliente', 'Cargas suspendidas', 'Quimicos'],
    ['Analisis de fallas', 'Aislamiento incorrecto', 'Lecciones de mantenimiento'],
  ),
  operator(
    'operator-hazmat',
    'Operador de Carga Peligrosa / IMDG',
    'Operador HAZ',
    ['Induccion HSSE', 'Reconocimiento IMDG', 'Segregacion', 'Etiquetado', 'Respuesta inicial', 'Escalamiento'],
    ['Kit de derrames', 'Contenedor danado', 'Sustancias especificas'],
    ['Simulacion de derrame', 'Casos IMDG', 'Senales de alarma temprana'],
  ),
  {
    id: 'supervisor',
    name: 'Supervisor Operativo',
    shortName: 'Supervisor',
    demoUser: 'Juan Perez',
    initials: 'JP',
    level: 'supervisor',
    decisionFocus: 'Que valido, que brecha cierro y cuando escalo.',
    terminal,
    campaign: 'Control de turno y competencias',
    mandatoryModules: ['Controles criticos', 'Permisos', 'Validacion de competencia', 'Stop Work', 'Gestion de turno'],
    conditionalModules: ['Contratistas', 'Izaje', 'Trabajos en altura', 'Energia almacenada'],
    optionalModules: ['Coaching con simuladores', 'Tendencias del turno', 'Lecciones aprendidas'],
    visibleDimensions: ['culture', 'prevent', 'intelligence', 'training', 'knowledge', 'advisor', 'operational'],
    informationalDimensions: ['immersive', 'regional'],
  },
  {
    id: 'contractor',
    name: 'Contratista',
    shortName: 'Contratista',
    demoUser: 'Usuario Contratista',
    initials: 'CT',
    level: 'contractor',
    decisionFocus: 'Que permiso tengo, que limite respeto y quien autoriza.',
    terminal,
    campaign: 'Ingreso y trabajo autorizado',
    mandatoryModules: ['Induccion HSSE', 'Contratistas', 'Permiso aplicable', 'EPP', 'Reporte y emergencia'],
    conditionalModules: ['Trabajos en altura', 'Energia almacenada', 'Cargas suspendidas', 'Trabajo en caliente'],
    optionalModules: ['Simulacion previa a tarea critica', 'Lecciones del sitio'],
    visibleDimensions: ['culture', 'prevent', 'training', 'knowledge', 'advisor', 'operational'],
    informationalDimensions: ['intelligence', 'immersive', 'regional'],
  },
  {
    id: 'hsse-local',
    name: 'HSSE Local',
    shortName: 'HSSE Local',
    demoUser: 'HSSE Buenos Aires',
    initials: 'HL',
    level: 'leader',
    decisionFocus: 'Que patron intervengo, que control verifico y que aprendizaje valido.',
    terminal,
    campaign: 'Control y aprendizaje local',
    mandatoryModules: ['Todos los requisitos HSSE aplicables', 'Validacion de evidencia', 'Analisis de patrones'],
    conditionalModules: ['Investigacion', 'Gestion de contratistas', 'Cambios operacionales'],
    optionalModules: ['Diseno de simulaciones', 'Benchmark local'],
    visibleDimensions: ['culture', 'prevent', 'intelligence', 'training', 'knowledge', 'advisor', 'immersive', 'operational', 'regional'],
    informationalDimensions: [],
  },
  {
    id: 'hsse-regional',
    name: 'HSSE Regional / Lider',
    shortName: 'HSSE Regional',
    demoUser: 'Regional Americas',
    initials: 'RA',
    level: 'leader',
    decisionFocus: 'Que brecha sistemica priorizo, donde asigno recursos y que practica escalo.',
    terminal: 'Americas',
    campaign: 'Regional HSSE learning loop',
    mandatoryModules: ['Gobernanza HSSE', 'Regional Analytics', 'Madurez de controles', 'Competencia por rol'],
    conditionalModules: ['Intervencion regional', 'Auditoria', 'Cambio de estandar'],
    optionalModules: ['Benchmark global', 'Inversion en simuladores'],
    visibleDimensions: ['culture', 'prevent', 'intelligence', 'training', 'knowledge', 'advisor', 'operational', 'regional'],
    informationalDimensions: ['immersive'],
  },
  {
    id: 'client-internal',
    name: 'Cliente / Equipo Interno',
    shortName: 'Equipo Interno',
    demoUser: 'Coordinacion Operativa',
    initials: 'CO',
    level: 'client',
    decisionFocus: 'Que impacto operativo existe y que restriccion debo coordinar.',
    terminal,
    campaign: 'Visibilidad y coordinacion segura',
    mandatoryModules: ['Induccion de acceso', 'Restricciones operativas', 'Canales de emergencia'],
    conditionalModules: ['Carga peligrosa', 'Visita operacional', 'Cambios de plan'],
    optionalModules: ['Sensibilizacion inmersiva', 'Lecciones compartidas'],
    visibleDimensions: ['culture', 'prevent', 'knowledge', 'operational'],
    informationalDimensions: ['intelligence', 'training', 'advisor', 'immersive', 'regional'],
  },
]

export const defaultRoleId: RoleId = 'operator-lashing'

export const getRoleProfile = (roleId: RoleId) => (
  roleProfiles.find((role) => role.id === roleId) ?? roleProfiles[0]
)
